AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'templates/**/*'
    - 'contacts/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 120

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false
